css:
  item:
    - static/css/bootstrap.css
    - static/css/aplayercss.css
    # - static/css/custom.css

js:
  head:
    - static/js/APlayer.js
    - static/js/Meting.js
  bottom:
    - static/js/fillword.js
    - static/js/highlight.js

highlight:
  color: 4ba7ee